### ISSUE TITLE
Installation guideline

### ISSUE THREAD

**Issue by JuliusWelzel** [neurogeriatricskiel/gamma_2024#1]
Hi @masoudabedinifar,

could you provide a detailed guide how to access the notebooks on colab. Right now as a novel Python user it might be difficult to do.

**Comment by masoudabedinifar** [comment]
Hi @JuliusWelzel ,

Thanks for your comment. I updated the Installation guidelines here [Readme](https://github.com/neurogeriatricskiel/gamma_2024) Could you please check the updates and see if they fulfill the requirement?

Best,
Masoud

**Comment by JuliusWelzel** [comment]
Colab part is better.
What to I have to do before I run it locally? Download it or git clone it?

**Comment by masoudabedinifar** [comment]
@JuliusWelzel I updated as [Readme](https://github.com/neurogeriatricskiel/gamma_2024). Could you please check it?
Thanks!

**Comment by JuliusWelzel** [comment]
Local installation adapted in https://github.com/neurogeriatricskiel/gamma_2024/commit/9ed7022fdd9391e667bb519c2d9964ae006c9a19 and colab instructions in https://github.com/neurogeriatricskiel/gamma_2024/commit/15fbbcf9253d1677fba9d36c7272ee325a208ba6.
